# docker-compose.yml
version: '3.8'

services:
  email-scraper:
    build: .
    container_name: email-scraper
    ports:
      - "8501:8501"
    volumes:
      - ./outputs:/app/outputs
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - scraper-network

networks:
  scraper-network:
    driver: bridge
