services:
  email-scraper:
    build: .
    container_name: email-scraper
    ports:
      - "8505:8501"  # Changed from 8501:8501 to 8505:8501
    volumes:
      - ./outputs:/app/outputs
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - scraper-network

networks:
  scraper-network:
    driver: bridge
